buildscript {
    repositories {
        mavenCentral()
        maven { url = 'https://maven.minecraftforge.net' }
        maven { url = 'https://files.minecraftforge.net/maven' }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.1-SNAPSHOT'
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'

version = '0.1.0'
group = 'com.stardustpvp'
archivesBaseName = 'StardustPvP'

sourceCompatibility = targetCompatibility = '1.8'

minecraft {
    // Published Maven coordinates for Forge 1.8.9.
    version = '1.8.9-11.15.1.2318-1.8.9'
    runDir = 'run'
    mappings = 'stable_22'
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.minecraftforge.net' }
}

dependencies {
    // OptiFine is intentionally documented as a local/development dependency.
    // Redistribution is not performed by this project.
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'mcversion', '1.8.9'

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version': project.version, 'mcversion': '1.8.9'
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}
